import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseArgs } from 'node:util';
import { stringify as yamlStringify } from 'yaml';
import { input } from '@inquirer/prompts';
import { cachedScan as defaultScan } from '../utils/scan-cache.js';
import { describeScanWarnings } from '../utils/scan-warnings.js';
import { pathExists } from '../utils/fs.js';
import { isInteractive as defaultIsInteractive } from '../utils/tty.js';
import { AGENT_HANDOFF_PREFIX } from '../utils/agent-handoff.js';
import { detectProjectState as defaultDetectProjectState } from '../utils/project-state.js';
import { buildAgentInstruction as buildGreenfieldAgentInstruction } from '../ai/prompts/greenfield.js';

export const HELP = `draftwise init — set up .draftwise/ for the current project

Usage:
  draftwise init                                       # auto-detects project state
  draftwise init --mode=greenfield --idea="<one-liner>"  # explicit override

Flags:
  --mode <greenfield|brownfield>     Override the auto-detected project state.
                                     "greenfield" = no code yet (Draftwise hands the
                                     stack/structure conversation to your coding agent).
                                     "brownfield" = existing codebase (Draftwise scans).
                                     Auto-detected from filesystem if omitted: zero
                                     source files → greenfield; otherwise brownfield.
  --idea "<text>"                    The project idea (greenfield only).

Detects whether the directory is empty (no code yet — "greenfield")
or contains an existing codebase ("brownfield") and routes
accordingly. Greenfield prints an instruction your coding agent
follows to walk through stack selection. Brownfield scans the
codebase. Refuses to overwrite an existing .draftwise/.

Non-TTY (CI, coding-agent shell): brownfield needs no further input
and runs straight through. Greenfield without --idea prints a
structured agent handoff so the host coding agent can ask the user
in chat and re-invoke with the flag.
`;

const ARG_OPTIONS = {
  mode: { type: 'string' },
  idea: { type: 'string' },
};

const VALID_MODES = ['greenfield', 'brownfield'];

const DRAFTWISE_GITIGNORE = `# Draftwise generates these locally; don't commit them.
.cache/
`;

const BROWNFIELD_OVERVIEW_PLACEHOLDER = `# Codebase overview

_This is a placeholder._ The full overview — flows, API surface, data model,
components, integrations — is generated by \`draftwise scan\`.

For now, \`draftwise init\` confirmed this repo contains source code and set
up \`.draftwise/\`. Run \`draftwise scan\` next to populate this file.
`;

function greenfieldAgentPlaceholder(idea) {
  return `# Greenfield plan — placeholder

> ${idea}

_This is a placeholder._ Your coding agent will replace this with the real
greenfield plan after walking through the three-phase conversation that
\`draftwise init\` just printed (clarifying questions → stack options →
chosen plan with directory structure and setup commands).

If you didn't run init inside an agentic IDE, you can ask any LLM to follow
the instruction printed by init — paste this idea and the instruction into
a chat and have it generate the plan, then save it back to this file.
`;
}

const DEFAULT_PROMPTS = {
  promptIdea: () =>
    input({
      message: 'In a sentence or two — what do you want to build?',
      validate: (v) =>
        v.trim().length > 0 ? true : 'Please describe the idea.',
    }),
};

function buildConfigYaml({ projectState, stack }) {
  const project = { state: projectState };
  if (stack) project.stack = stack;
  return yamlStringify({ project });
}

function buildInitHandoff(mode, modeSource) {
  const detectedLabel =
    mode === 'greenfield'
      ? 'new project (no source code in this directory yet)'
      : 'existing codebase (source files already present)';
  const detectedLine =
    modeSource === 'detected'
      ? `Detected: ${detectedLabel}. Override with --mode=${mode === 'greenfield' ? 'brownfield' : 'greenfield'} if wrong.`
      : `Project state set via --mode: ${detectedLabel}.`;

  return [
    AGENT_HANDOFF_PREFIX,
    '',
    '---',
    'INIT — answer in chat, then re-invoke draftwise init with the matching flag',
    '',
    detectedLine,
    '',
    '1. What do you want to build? A sentence or two — your coding agent will ask follow-up questions on stack and structure once init finishes.',
    '',
    'INSTRUCTION',
    'Once you have an answer from the user, re-invoke draftwise init with:',
    '',
    '  draftwise init --mode=greenfield --idea="<one-liner>"',
    '',
    'Notes:',
    '- --mode is auto-detected from the filesystem (zero source files → greenfield; otherwise brownfield). Pass it only to override.',
    '- --idea is required when the project is greenfield.',
  ].join('\n');
}

async function runBrownfield({ cwd, log, scan, draftwiseDir }) {
  log('');
  log('Scanning repo for source files...');
  const result = await scan(cwd);
  if (!result.files || result.files.length === 0) {
    throw new Error(
      `No source files found under ${cwd}. Either start in greenfield mode or run \`draftwise init\` from your code repo.`,
    );
  }
  log(
    `Found ${result.files.length} source file${result.files.length === 1 ? '' : 's'}.`,
  );
  for (const warning of describeScanWarnings(result, {
    includeFrameworkHint: true,
  })) {
    log(warning);
  }
  log('');

  await mkdir(join(draftwiseDir, 'specs'), { recursive: true });
  await writeFile(
    join(draftwiseDir, 'overview.md'),
    BROWNFIELD_OVERVIEW_PLACEHOLDER,
    'utf8',
  );
  await writeFile(
    join(draftwiseDir, 'config.yaml'),
    buildConfigYaml({ projectState: 'brownfield' }),
    'utf8',
  );
  await writeFile(join(draftwiseDir, '.gitignore'), DRAFTWISE_GITIGNORE, 'utf8');

  log('Created .draftwise/ with:');
  log('  • overview.md   (placeholder — `draftwise scan` will fill it in)');
  log('  • specs/        (your specs will live here)');
  log('  • config.yaml   (project state)');
  log('  • .gitignore    (excludes .cache/ from version control)');
  log('');
  log(
    'Run draftwise commands inside your coding agent (Claude Code, Cursor, etc.).',
  );
  log('');
  log('Next: draftwise scan');
}

async function runGreenfield({
  log,
  draftwiseDir,
  prompts,
  isInteractive,
  ideaFlag,
}) {
  log('');

  let idea = ideaFlag;
  if (idea === undefined || idea === null) {
    if (isInteractive()) {
      idea = await prompts.promptIdea();
    } else {
      throw new Error(
        'Greenfield init needs --idea "<one-liner describing what you want to build>". Pass it as a flag, or run init in an interactive terminal.',
      );
    }
  }
  if (typeof idea !== 'string' || idea.trim().length === 0) {
    throw new Error('--idea must be a non-empty string.');
  }

  log('');
  log('Handing the greenfield conversation off to your coding agent.');
  log(AGENT_HANDOFF_PREFIX);
  log('');
  log('---');
  log(`IDEA: ${idea}`);
  log('');
  log('INSTRUCTION');
  log(buildGreenfieldAgentInstruction(idea));
  log('');

  await mkdir(join(draftwiseDir, 'specs'), { recursive: true });
  await writeFile(
    join(draftwiseDir, 'overview.md'),
    greenfieldAgentPlaceholder(idea),
    'utf8',
  );
  await writeFile(
    join(draftwiseDir, 'config.yaml'),
    buildConfigYaml({ projectState: 'greenfield' }),
    'utf8',
  );
  await writeFile(join(draftwiseDir, '.gitignore'), DRAFTWISE_GITIGNORE, 'utf8');

  log('Created .draftwise/ with:');
  log('  • overview.md   (placeholder — your agent will rewrite from the conversation)');
  log('  • specs/        (your specs will live here)');
  log('  • config.yaml   (project state)');
  log('  • .gitignore    (excludes .cache/ from version control)');
  log('');
  log('Run draftwise commands inside your coding agent (Claude Code, Cursor, etc.).');
}

export default async function init(args = [], deps = {}) {
  const cwd = deps.cwd ?? process.cwd();
  const log = deps.log ?? ((msg) => console.error(msg));
  const scan = deps.scan ?? defaultScan;
  const isInteractive = deps.isInteractive ?? defaultIsInteractive;
  const detectProjectState =
    deps.detectProjectState ?? defaultDetectProjectState;
  const prompts = { ...DEFAULT_PROMPTS, ...(deps.prompts ?? {}) };

  let parsed;
  try {
    parsed = parseArgs({
      args,
      options: ARG_OPTIONS,
      allowPositionals: true,
      strict: true,
    });
  } catch (err) {
    throw new Error(`Invalid arguments to draftwise init: ${err.message}`, {
      cause: err,
    });
  }
  const flags = parsed.values;

  const draftwiseDir = join(cwd, '.draftwise');
  if (await pathExists(draftwiseDir)) {
    throw new Error(
      '.draftwise/ already exists in this directory. Delete it or run from a different directory to re-init.',
    );
  }

  // Resolve project state before anything else — by --mode flag (with
  // validation) or by walking the filesystem for source files.
  let projectState;
  let modeSource;
  if (flags.mode !== undefined) {
    if (!VALID_MODES.includes(flags.mode)) {
      throw new Error(
        `Invalid --mode value "${flags.mode}". Must be one of: ${VALID_MODES.join(', ')}.`,
      );
    }
    projectState = flags.mode;
    modeSource = 'flag';
  } else {
    projectState = await detectProjectState(cwd);
    modeSource = 'detected';
  }

  // Non-TTY structured handoff: greenfield without --idea is the only
  // remaining case where init can't proceed without asking the user. Print
  // the question in AGENT_HANDOFF_PREFIX format so the host coding agent
  // (Claude Code, Cursor, etc.) reads it from stderr, asks the user in chat,
  // and re-invokes with --idea filled in.
  if (
    !isInteractive() &&
    projectState === 'greenfield' &&
    !flags.idea
  ) {
    log(buildInitHandoff(projectState, modeSource));
    return;
  }

  log('Welcome to Draftwise. Setting up .draftwise/ for this project.');
  log('');

  if (modeSource === 'detected') {
    if (projectState === 'greenfield') {
      log(
        'Detected: new project — no source files yet. Setting up for greenfield init.',
      );
      log('  Override with --mode=brownfield if you meant an existing codebase.');
    } else {
      log(
        'Detected: existing codebase — source files already in this directory. Setting up for brownfield init.',
      );
      log('  Override with --mode=greenfield to start fresh instead.');
    }
    log('');
  }

  if (projectState === 'brownfield') {
    return runBrownfield({ cwd, log, scan, draftwiseDir });
  }
  return runGreenfield({
    log,
    draftwiseDir,
    prompts,
    isInteractive,
    ideaFlag: flags.idea,
  });
}
