import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseArgs } from 'node:util';
import { stringify as yamlStringify } from 'yaml';
import { select, input } from '@inquirer/prompts';
import { cachedScan as defaultScan } from '../utils/scan-cache.js';
import { complete as defaultComplete } from '../ai/provider.js';
import { describeScanWarnings } from '../utils/scan-warnings.js';
import { pathExists } from '../utils/fs.js';
import { isInteractive as defaultIsInteractive } from '../utils/tty.js';
import { AGENT_HANDOFF_PREFIX } from '../utils/agent-handoff.js';
import {
  QUESTIONS_SYSTEM,
  STACKS_SYSTEM,
  buildQuestionsPrompt,
  buildStacksPrompt,
  parseQuestionsResponse,
  parseStacksResponse,
  buildOverviewMarkdown,
  buildAgentInstruction as buildGreenfieldAgentInstruction,
} from '../ai/prompts/greenfield.js';

export const HELP = `draft init — set up .draftwise/ for the current project

Usage:
  draft init                                       # interactive (TTY only)
  draft init --mode=brownfield --ai-mode=agent
  draft init --mode=greenfield --ai-mode=api \\
    --provider=claude --idea="<one-liner>"

Flags:
  --mode <greenfield|brownfield>     Project state.
  --ai-mode <agent|api>              How Draftwise calls the AI.
  --provider <claude|openai|gemini>  AI provider (api mode only).
  --api-key-env <VAR>                Env var holding the API key (api mode only).
                                     Defaults to ANTHROPIC_API_KEY / OPENAI_API_KEY /
                                     GEMINI_API_KEY based on --provider.
  --idea "<text>"                    The project idea (greenfield only).
  --stack <name>                     Pre-pick a stack by name (greenfield + api).
                                     Skips the picker; must match one of the model's
                                     proposed stack names.
  --answers <json|@file>             JSON array of answers to greenfield clarifying
                                     questions, or @path/to/answers.json. Used in
                                     greenfield + api when you've pre-collected the
                                     answers (e.g. via a slash-command wrapper).

Asks whether the project is greenfield (no code yet) or brownfield
(existing codebase) and routes accordingly. Greenfield walks you
through stack selection with rationale, pros, and cons. Brownfield
scans the codebase. Refuses to overwrite an existing .draftwise/.

Non-TTY (CI, coding-agent shell): every value must be supplied via
flags. A missing required flag errors with a usage hint instead of
hanging on a prompt.
`;

const ARG_OPTIONS = {
  mode: { type: 'string' },
  'ai-mode': { type: 'string' },
  provider: { type: 'string' },
  'api-key-env': { type: 'string' },
  idea: { type: 'string' },
  stack: { type: 'string' },
  answers: { type: 'string' },
};

const VALID_MODES = ['greenfield', 'brownfield'];
const VALID_AI_MODES = ['agent', 'api'];
const VALID_PROVIDERS = ['claude', 'openai', 'gemini'];

const ENV_VAR_BY_PROVIDER = {
  claude: 'ANTHROPIC_API_KEY',
  openai: 'OPENAI_API_KEY',
  gemini: 'GEMINI_API_KEY',
};

const DRAFTWISE_GITIGNORE = `# Draftwise generates these locally; don't commit them.
.cache/
`;

const BROWNFIELD_OVERVIEW_PLACEHOLDER = `# Codebase overview

_This is a placeholder._ The full overview — flows, API surface, data model,
components, integrations — is generated by \`draft scan\`.

For now, \`draft init\` confirmed this repo contains source code and set
up \`.draftwise/\`. Run \`draft scan\` next to populate this file.
`;

function greenfieldAgentPlaceholder(idea) {
  return `# Greenfield plan — placeholder

> ${idea}

_This is a placeholder._ Your coding agent will replace this with the real
greenfield plan after walking through the three-phase conversation that
\`draft init\` just printed (clarifying questions → stack options →
chosen plan with directory structure and setup commands).

If you didn't run init inside an agentic IDE, you can ask any LLM to follow
the instruction printed by init — paste this idea and the instruction into
a chat and have it generate the plan, then save it back to this file.
`;
}

const DEFAULT_PROMPTS = {
  promptProjectState: () =>
    select({
      message: 'What stage is your project at?',
      choices: [
        {
          name: 'Greenfield — I have an idea but no code yet',
          value: 'greenfield',
          description:
            'Draftwise will help pick a stack and propose initial structure',
        },
        {
          name: 'Brownfield — I have an existing codebase',
          value: 'brownfield',
          description: 'Draftwise will scan the code and produce an overview',
        },
      ],
      default: 'brownfield',
    }),
  promptMode: () =>
    select({
      message: 'How should Draftwise call the AI?',
      choices: [
        {
          name: 'Inside a coding agent (Claude Code, Cursor, Antigravity, etc.)',
          value: 'agent',
          description: "The agent's existing model handles reasoning",
        },
        {
          name: 'Direct API call (with your own API key)',
          value: 'api',
          description: 'Draftwise calls the model API directly',
        },
      ],
      default: 'agent',
    }),
  promptProvider: () =>
    select({
      message: 'Which AI provider?',
      choices: [
        { name: 'Claude (Anthropic) — fully wired', value: 'claude' },
        { name: 'OpenAI — adapter not yet implemented', value: 'openai' },
        { name: 'Gemini (Google) — adapter not yet implemented', value: 'gemini' },
      ],
    }),
  promptApiKeyEnv: ({ provider, suggested }) =>
    input({
      message: `Which environment variable holds your ${provider} API key?`,
      default: suggested,
    }),
  promptIdea: () =>
    input({
      message: 'In a sentence or two — what do you want to build?',
      validate: (v) =>
        v.trim().length > 0 ? true : 'Please describe the idea.',
    }),
  askGreenfieldQuestion: ({ index, total, text, why }) =>
    input({
      message: `Q${index + 1}/${total} — ${text}\n  Why: ${why}\n  (press enter to skip)`,
    }),
  pickStack: ({ stackOptions }) =>
    select({
      message: 'Which stack do you want to go with?',
      choices: stackOptions.map((s) => ({
        name: s.name,
        value: s.name,
        description: s.summary,
      })),
    }),
};

function buildConfigYaml({ mode, provider, apiKeyEnv, projectState, stack }) {
  const ai = { mode };
  if (mode === 'api') {
    ai.provider = provider;
    ai.api_key_env = apiKeyEnv;
    ai.model = '';
  }
  const project = { state: projectState };
  if (stack) project.stack = stack;
  return yamlStringify({ ai, project });
}

function formatStackForDisplay(opt, index) {
  const lines = [
    '',
    `── Option ${index + 1}: ${opt.name} ──`,
    opt.summary,
    '',
    `Why this fits: ${opt.rationale}`,
    '',
    'Pros:',
    ...(opt.pros ?? []).map((p) => `  + ${p}`),
    '',
    'Cons:',
    ...(opt.cons ?? []).map((c) => `  - ${c}`),
  ];
  return lines.join('\n');
}

async function loadAnswersFlag(value) {
  if (!value) return null;
  let raw;
  if (value.startsWith('@')) {
    try {
      raw = await readFile(value.slice(1), 'utf8');
    } catch (err) {
      throw new Error(
        `Could not read --answers file ${value.slice(1)}: ${err.message}`,
        { cause: err },
      );
    }
  } else {
    raw = value;
  }
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new Error(
      `--answers must be a JSON array (or @path-to-json-file). ${err.message}`,
      { cause: err },
    );
  }
  if (!Array.isArray(parsed) || !parsed.every((a) => typeof a === 'string')) {
    throw new Error('--answers must be a JSON array of strings.');
  }
  return parsed;
}

// Resolves a value from (1) a flag, (2) a TTY prompt, or (3) errors out with a
// usage hint when neither is available. Keeps the "flags-first, prompts as
// fallback" pattern in one place so every input handles non-TTY identically.
//
// In normal flow this throws on the non-TTY+missing case as a backstop —
// `init`'s entry point catches that case earlier with a structured handoff
// (see needsHandoff / buildInitHandoff below) and returns before reaching
// here. The throw stays as defensive coverage for fields the handoff doesn't
// account for.
async function resolveValue({
  flagName,
  flagValue,
  promptFn,
  isInteractive,
  validValues,
  missingHint,
}) {
  if (flagValue !== undefined && flagValue !== null) {
    if (validValues && !validValues.includes(flagValue)) {
      throw new Error(
        `Invalid --${flagName} value "${flagValue}". Must be one of: ${validValues.join(', ')}.`,
      );
    }
    return flagValue;
  }
  if (isInteractive()) {
    return promptFn();
  }
  throw new Error(missingHint);
}

// True when init can't proceed in non-TTY without asking the user something.
// Drives the structured-handoff path (see buildInitHandoff) — the host coding
// agent reads the handoff, asks the user in chat, and re-invokes draft init
// with the collected flags.
function needsHandoff(flags) {
  if (!flags.mode) return true;
  if (!flags['ai-mode']) return true;
  if (flags['ai-mode'] === 'api' && !flags.provider) return true;
  if (flags.mode === 'greenfield' && !flags.idea) return true;
  return false;
}

// Builds the structured handoff printed when init can't proceed in non-TTY.
// Format follows the same AGENT_HANDOFF_PREFIX pattern Draftwise already uses
// elsewhere — orienting line, fenced section, INSTRUCTION block — so the host
// agent (Claude Code, Cursor, etc.) recognizes it as a "ask the user, then
// re-invoke" handoff. Only lists questions for fields that aren't already
// supplied; conditional questions get a "(only if ...)" marker when the
// upstream answer isn't known yet.
function buildInitHandoff(flags) {
  const askMode = !flags.mode;
  const askAiMode = !flags['ai-mode'];
  const askProvider = flags['ai-mode'] !== 'agent' && !flags.provider;
  const askIdea = flags.mode !== 'brownfield' && !flags.idea;

  const rawQuestions = [];
  if (askMode) {
    rawQuestions.push(
      'Project state — **greenfield** (no code yet) or **brownfield** (existing codebase)?',
    );
  }
  if (askAiMode) {
    rawQuestions.push(
      'AI mode — **agent** (the host coding agent — Claude Code, Cursor, etc. — handles reasoning) or **api** (Draftwise calls a model directly with your API key)?',
    );
  }
  if (askProvider) {
    const conditional =
      flags['ai-mode'] === undefined ? ' (only if you picked **api** above)' : '';
    rawQuestions.push(
      `AI provider — **claude** (the only one fully wired today), openai, or gemini?${conditional}`,
    );
  }
  if (askIdea) {
    const conditional =
      flags.mode === undefined ? ' (only if you picked **greenfield** above)' : '';
    rawQuestions.push(
      `What do you want to build?${conditional} A sentence or two — the model will ask follow-up questions on stack and structure.`,
    );
  }
  const questions = rawQuestions.map((q, i) => `${i + 1}. ${q}`);

  const lines = [
    AGENT_HANDOFF_PREFIX,
    '',
    '---',
    'INIT — answer these in chat, then re-invoke draft init with the matching flags',
    '',
    ...questions,
    '',
    'INSTRUCTION',
    'Once you have answers from the user, re-invoke draft init with the corresponding flags:',
    '',
    '  draft init --mode=<greenfield|brownfield> --ai-mode=<agent|api>',
    '             [--provider=<claude|openai|gemini>] [--api-key-env=<VAR>]',
    '             [--idea="<one-liner>"] [--stack="<name>"] [--answers @path/to/answers.json]',
    '',
    'Notes:',
    '- --provider only applies when --ai-mode=api.',
    '- --api-key-env defaults to ANTHROPIC_API_KEY / OPENAI_API_KEY / GEMINI_API_KEY based on --provider; pass it only to override.',
    '- --idea is required for --mode=greenfield.',
    '- For greenfield + api: --stack and --answers are optional first time. Without them, init picks the first proposed stack and leaves clarifying-question answers blank. Re-invoke with both for a richer plan.',
  ];
  return lines.join('\n');
}

async function runBrownfield({ cwd, log, scan, draftwiseDir, aiConfig }) {
  log('');
  log('Scanning repo for source files...');
  const result = await scan(cwd);
  if (!result.files || result.files.length === 0) {
    throw new Error(
      `No source files found under ${cwd}. Either start in greenfield mode or run \`draft init\` from your code repo.`,
    );
  }
  log(
    `Found ${result.files.length} source file${result.files.length === 1 ? '' : 's'}.`,
  );
  for (const warning of describeScanWarnings(result, {
    includeFrameworkHint: true,
  })) {
    log(warning);
  }
  log('');

  await mkdir(join(draftwiseDir, 'specs'), { recursive: true });
  await writeFile(
    join(draftwiseDir, 'overview.md'),
    BROWNFIELD_OVERVIEW_PLACEHOLDER,
    'utf8',
  );
  await writeFile(
    join(draftwiseDir, 'config.yaml'),
    buildConfigYaml({ ...aiConfig, projectState: 'brownfield' }),
    'utf8',
  );
  await writeFile(join(draftwiseDir, '.gitignore'), DRAFTWISE_GITIGNORE, 'utf8');

  log('Created .draftwise/ with:');
  log('  • overview.md   (placeholder — `draft scan` will fill it in)');
  log('  • specs/        (your specs will live here)');
  log('  • config.yaml   (AI mode + project state)');
  log('  • .gitignore    (excludes .cache/ from version control)');
  log('');
  if (aiConfig.mode === 'api') {
    log(
      `Make sure ${aiConfig.apiKeyEnv} is set in your environment before running other commands.`,
    );
  } else {
    log(
      'Run draft commands inside your coding agent (Claude Code, Cursor, etc.).',
    );
  }
  log('');
  log('Next: draft scan');
}

async function runGreenfield({
  log,
  complete,
  draftwiseDir,
  aiConfig,
  prompts,
  isInteractive,
  ideaFlag,
  stackFlag,
  answersFlag,
}) {
  log('');

  const idea = await resolveValue({
    flagName: 'idea',
    flagValue: ideaFlag,
    promptFn: () => prompts.promptIdea(),
    isInteractive,
    missingHint:
      'Greenfield init needs --idea "<one-liner describing what you want to build>". Pass it as a flag, or run init in an interactive terminal.',
  });
  if (typeof idea !== 'string' || idea.trim().length === 0) {
    throw new Error('--idea must be a non-empty string.');
  }

  if (aiConfig.mode === 'agent') {
    log('');
    log('Agent mode — handing the greenfield conversation off to your coding agent.');
    log(AGENT_HANDOFF_PREFIX);
    log('');
    log('---');
    log(`IDEA: ${idea}`);
    log('');
    log('INSTRUCTION');
    log(buildGreenfieldAgentInstruction(idea));
    log('');

    await mkdir(join(draftwiseDir, 'specs'), { recursive: true });
    await writeFile(
      join(draftwiseDir, 'overview.md'),
      greenfieldAgentPlaceholder(idea),
      'utf8',
    );
    await writeFile(
      join(draftwiseDir, 'config.yaml'),
      buildConfigYaml({ ...aiConfig, projectState: 'greenfield' }),
      'utf8',
    );
    await writeFile(
      join(draftwiseDir, '.gitignore'),
      DRAFTWISE_GITIGNORE,
      'utf8',
    );

    log('Created .draftwise/ with:');
    log('  • overview.md   (placeholder — your agent will rewrite from the conversation)');
    log('  • specs/        (your specs will live here)');
    log('  • config.yaml   (AI mode + project state)');
    log('  • .gitignore    (excludes .cache/ from version control)');
    log('');
    log('Run draft commands inside your coding agent (Claude Code, Cursor, etc.).');
    return;
  }

  log('');
  log('Generating clarifying questions...');
  const questionsText = await complete({
    provider: aiConfig.provider,
    apiKeyEnv: aiConfig.apiKeyEnv,
    model: '',
    system: QUESTIONS_SYSTEM,
    prompt: buildQuestionsPrompt(idea),
  });
  const { projectTitle, questions } = parseQuestionsResponse(questionsText);

  log('');
  log(`Got it — "${projectTitle}". ${questions.length} questions before I propose stacks:`);
  log('');

  let answers;
  if (answersFlag) {
    answers = answersFlag.slice(0, questions.length);
    while (answers.length < questions.length) answers.push('');
  } else if (isInteractive()) {
    answers = [];
    for (let i = 0; i < questions.length; i++) {
      const q = questions[i];
      const answer = await prompts.askGreenfieldQuestion({
        index: i,
        total: questions.length,
        text: q.text,
        why: q.why,
      });
      answers.push(answer);
    }
  } else {
    // Non-TTY without --answers: model gets no answers. Init still produces a
    // plan, but the stack rationale will be generic. Pass --answers next time.
    answers = questions.map(() => '');
  }

  log('');
  log('Thinking about stack options...');
  const stacksText = await complete({
    provider: aiConfig.provider,
    apiKeyEnv: aiConfig.apiKeyEnv,
    model: '',
    system: STACKS_SYSTEM,
    prompt: buildStacksPrompt({ idea, projectTitle, questions, answers }),
  });
  const stackOptions = parseStacksResponse(stacksText);

  log('');
  for (let i = 0; i < stackOptions.length; i++) {
    log(formatStackForDisplay(stackOptions[i], i));
  }
  log('');

  let chosenName;
  if (stackFlag) {
    if (!stackOptions.some((s) => s.name === stackFlag)) {
      const available = stackOptions.map((s) => s.name).join(', ');
      throw new Error(
        `--stack "${stackFlag}" doesn't match any proposed option. Available: ${available}`,
      );
    }
    chosenName = stackFlag;
  } else if (isInteractive()) {
    chosenName = await prompts.pickStack({ stackOptions });
  } else {
    // Non-TTY without --stack: pick the first option. Caller can re-run with
    // --stack=<name> if they want a different one.
    chosenName = stackOptions[0].name;
    log(`No --stack flag and not interactive — picking first option: ${chosenName}`);
  }
  const chosen = stackOptions.find((s) => s.name === chosenName);
  if (!chosen) {
    throw new Error(
      `Internal error: chosen stack "${chosenName}" not found in options.`,
    );
  }

  const overview = buildOverviewMarkdown({
    projectTitle,
    idea,
    questions,
    answers,
    chosen,
  });

  await mkdir(join(draftwiseDir, 'specs'), { recursive: true });
  await writeFile(join(draftwiseDir, 'overview.md'), overview, 'utf8');
  await writeFile(
    join(draftwiseDir, 'config.yaml'),
    buildConfigYaml({
      ...aiConfig,
      projectState: 'greenfield',
      stack: chosen.name,
    }),
    'utf8',
  );
  await writeFile(join(draftwiseDir, '.gitignore'), DRAFTWISE_GITIGNORE, 'utf8');

  await writeFile(
    join(draftwiseDir, 'scaffold.json'),
    JSON.stringify(
      {
        stack: chosen.name,
        summary: chosen.summary,
        directory_structure: chosen.directory_structure ?? '',
        initial_files: chosen.initial_files ?? [],
        setup_commands: chosen.setup_commands ?? [],
      },
      null,
      2,
    ),
    'utf8',
  );

  log('');
  log(`Picked: ${chosen.name}`);
  log('');
  log('Created .draftwise/ with:');
  log(
    `  • overview.md     (greenfield plan: idea, discovery, ${chosen.name}, directory structure, setup)`,
  );
  log('  • specs/          (your specs will live here)');
  log('  • config.yaml     (AI mode + project state + stack)');
  log('  • scaffold.json   (structured plan for `draft scaffold`)');
  log('');
  log('Next steps:');
  log('  1. Open .draftwise/overview.md and run the setup commands.');
  log(
    '  2. (Optional) `draft scaffold` to create the user-written initial files.',
  );
  log(
    '  3. Once you have some code, `draft scan` will refresh this overview.',
  );
  log('  4. `draft new "<feature idea>"` to draft your first feature spec.');
}

export default async function init(args = [], deps = {}) {
  const cwd = deps.cwd ?? process.cwd();
  const log = deps.log ?? ((msg) => console.error(msg));
  const scan = deps.scan ?? defaultScan;
  const complete = deps.complete ?? defaultComplete;
  const isInteractive = deps.isInteractive ?? defaultIsInteractive;
  const prompts = { ...DEFAULT_PROMPTS, ...(deps.prompts ?? {}) };

  let parsed;
  try {
    parsed = parseArgs({
      args,
      options: ARG_OPTIONS,
      allowPositionals: true,
      strict: true,
    });
  } catch (err) {
    throw new Error(`Invalid arguments to draft init: ${err.message}`, {
      cause: err,
    });
  }
  const flags = parsed.values;
  const answersFlag = await loadAnswersFlag(flags.answers);

  const draftwiseDir = join(cwd, '.draftwise');
  if (await pathExists(draftwiseDir)) {
    throw new Error(
      '.draftwise/ already exists in this directory. Delete it or run from a different directory to re-init.',
    );
  }

  // Non-TTY structured handoff: when stdin isn't interactive and init needs
  // to ask the user something, print the questions in the AGENT_HANDOFF_PREFIX
  // format so the host coding agent (Claude Code, Cursor, etc.) can read them
  // from stderr, ask the user in chat, and re-invoke `draft init` with the
  // collected flags. Falls through to normal flag-or-prompt resolution when
  // every required value is already supplied.
  if (!isInteractive() && needsHandoff(flags)) {
    log(buildInitHandoff(flags));
    return;
  }

  log('Welcome to Draftwise. A few quick questions before we set you up.');
  log('');

  const projectState = await resolveValue({
    flagName: 'mode',
    flagValue: flags.mode,
    promptFn: () => prompts.promptProjectState(),
    isInteractive,
    validValues: VALID_MODES,
    missingHint:
      'Missing --mode flag. Pass --mode=greenfield (no code yet) or --mode=brownfield (existing codebase).',
  });

  const aiMode = await resolveValue({
    flagName: 'ai-mode',
    flagValue: flags['ai-mode'],
    promptFn: () => prompts.promptMode(),
    isInteractive,
    validValues: VALID_AI_MODES,
    missingHint:
      'Missing --ai-mode flag. Pass --ai-mode=agent (Claude Code/Cursor handles reasoning) or --ai-mode=api (Draftwise calls a model directly).',
  });

  let aiConfig;
  if (aiMode === 'agent') {
    aiConfig = { mode: 'agent' };
  } else {
    const provider = await resolveValue({
      flagName: 'provider',
      flagValue: flags.provider,
      promptFn: () => prompts.promptProvider(),
      isInteractive,
      validValues: VALID_PROVIDERS,
      missingHint:
        'Missing --provider flag (required when --ai-mode=api). Pass --provider=claude (or openai/gemini once those adapters are wired up).',
    });
    const suggested = ENV_VAR_BY_PROVIDER[provider];
    let apiKeyEnv = flags['api-key-env'];
    if (!apiKeyEnv) {
      if (isInteractive()) {
        apiKeyEnv = await prompts.promptApiKeyEnv({ provider, suggested });
      } else {
        // Non-TTY default — the provider's standard env var name. User can
        // override with --api-key-env if they use a custom name.
        apiKeyEnv = suggested;
      }
    }
    aiConfig = { mode: 'api', provider, apiKeyEnv };
  }

  if (projectState === 'brownfield') {
    return runBrownfield({ cwd, log, scan, draftwiseDir, aiConfig });
  }
  return runGreenfield({
    log,
    complete,
    draftwiseDir,
    aiConfig,
    prompts,
    isInteractive,
    ideaFlag: flags.idea,
    stackFlag: flags.stack,
    answersFlag,
  });
}
