import { readFile, writeFile, mkdir, access } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { confirm } from '@inquirer/prompts';

const DEFAULT_PROMPTS = {
  confirmScaffold: ({ stack, fileCount }) =>
    confirm({
      message: `About to create ${fileCount} file${fileCount === 1 ? '' : 's'} for the "${stack}" plan. If your setup commands include a project scaffolder (e.g. create-next-app, create-vite), run those FIRST — this will not overwrite existing files but it may interfere with a fresh scaffolder run. Proceed?`,
      default: false,
    }),
};

async function pathExists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

function placeholderFor(path, purpose) {
  const ext = path.slice(path.lastIndexOf('.')).toLowerCase();
  const note = purpose ? ` ${purpose}` : '';
  switch (ext) {
    case '.ts':
    case '.tsx':
    case '.js':
    case '.jsx':
    case '.mjs':
    case '.cjs':
      return `// TODO:${note}\n`;
    case '.py':
      return `# TODO:${note}\n`;
    case '.md':
      return `# ${purpose || path}\n\n_TODO_\n`;
    case '.json':
      return '{}\n';
    case '.yml':
    case '.yaml':
      return purpose ? `# ${purpose}\n` : '';
    case '.html':
      return '<!doctype html>\n<html>\n<head><meta charset="utf-8"></head>\n<body></body>\n</html>\n';
    case '.css':
    case '.scss':
      return purpose ? `/* ${purpose} */\n` : '';
    default:
      return '';
  }
}

export default async function scaffoldCommand(_args = [], deps = {}) {
  const cwd = deps.cwd ?? process.cwd();
  const log = deps.log ?? ((msg) => console.log(msg));
  const prompts = { ...DEFAULT_PROMPTS, ...(deps.prompts ?? {}) };

  const draftwiseDir = join(cwd, '.draftwise');
  if (!(await pathExists(draftwiseDir))) {
    throw new Error('.draftwise/ not found. Run `draftwise init` first.');
  }

  const scaffoldPath = join(draftwiseDir, 'scaffold.json');
  if (!(await pathExists(scaffoldPath))) {
    throw new Error(
      '.draftwise/scaffold.json not found. This file is generated by `draftwise init` in greenfield mode. If you ran init in agent mode, ask your coding agent to write scaffold.json from the conversation, or write it manually.',
    );
  }

  let plan;
  try {
    const raw = await readFile(scaffoldPath, 'utf8');
    plan = JSON.parse(raw);
  } catch (err) {
    throw new Error(`Failed to parse .draftwise/scaffold.json: ${err.message}`);
  }

  const initialFiles = Array.isArray(plan.initial_files) ? plan.initial_files : [];
  if (initialFiles.length === 0) {
    log('scaffold.json has no initial_files to create. Nothing to do.');
    return;
  }

  log(`Stack: ${plan.stack ?? '(unknown)'}`);
  if (plan.summary) log(plan.summary);
  log('');
  log(`Initial files to create (${initialFiles.length}):`);
  for (const f of initialFiles) {
    log(`  • ${f.path}${f.purpose ? `  — ${f.purpose}` : ''}`);
  }
  log('');

  const proceed = await prompts.confirmScaffold({
    stack: plan.stack ?? 'project',
    fileCount: initialFiles.length,
  });
  if (!proceed) {
    log('Aborted. No files were written.');
    return;
  }

  log('');
  let created = 0;
  let skipped = 0;
  for (const f of initialFiles) {
    if (!f.path || typeof f.path !== 'string') continue;
    const fullPath = join(cwd, f.path);
    if (await pathExists(fullPath)) {
      log(`  ~ skipped (exists): ${f.path}`);
      skipped++;
      continue;
    }
    await mkdir(dirname(fullPath), { recursive: true });
    await writeFile(fullPath, placeholderFor(f.path, f.purpose), 'utf8');
    log(`  + created: ${f.path}`);
    created++;
  }

  log('');
  log(`Done — ${created} created, ${skipped} skipped.`);

  const setupCommands = Array.isArray(plan.setup_commands)
    ? plan.setup_commands
    : [];
  if (setupCommands.length > 0) {
    log('');
    log('Setup commands (run these manually if you haven\'t already):');
    for (const cmd of setupCommands) log(`  $ ${cmd}`);
  }
}
